/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Master_start_walk_stop_root-animation_110126.glb -o src/components/MasterRoot.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Master_start_walk_stop_root-animation_110126.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.root} />
          <skinnedMesh name="material001" geometry={nodes.material001.geometry} material={materials['Material.001']} skeleton={nodes.material001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Master_start_walk_stop_root-animation_110126.glb')
